### ISSUE TITLE
Getting 404 Error From Malformed fetchMessage() Request

### ISSUE THREAD

**Issue by ZaneVonDomin** [zaida04/g.js-self#10]
The get() url for fetchMessage() has a `&` instead of a `?` for the query causing a malformed request. 

> https://github.com/zaida04/guilded.js/blob/master/packages/guilded.js/lib/structures/managers/ChannelManager.ts#L63

**Comment by zaida04** [comment]
resolved in cf9c30662430366e04634fe59c7f58042841344f, will do a release shortly.
