### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Natemo2625** [zaida04/g.js-self#6]
when this finished will i be able to easily convert my discord.js bot to work with this? also i know this is very early to be asking something like this, but will there be something similar to discord.js-commando? (possibly named guilded.js-commando)

**Comment by zaida04** [comment]
The library itself is already heavily modeled after Discord.js, and the docs are always a resource for help converting your code. I don't know how to gauge whether it would be _easy_, so I can't really answer that. There are plans to have a framework modelled after [Akairo](https://github.com/discord-akairo/discord-akairo), not Commando. But that will most likely come **after** the actual Guilded Bot API is released.

**Comment by Natemo2625** [comment]
ah alright
